### ISSUE TITLE
oBG2 spells bugs

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/iwdification#14]
The following spells have some bugs on oBG2 (with component 80):

- `Mold Touch`: unknown Opcode 324
- `Storm shell`: unknown Opcode 321 and has no icon - it is needed for ds - could be `Protected from the Elements (76)`
- `Lich Touch`: the spell/item has no icons for the paralysis immunity and the weapon (ltouch.itm) has a base attack power of 1d2 in addition to magical damages in ltouch.spl
- `circle of bones` has no icon - it is needed for ds - could be `Held (13)`
- `shout` has no icon for deafness effect
- `Gshout` has no icon for deafness effect
- `dart of bones` strength malus effect has no icon
- slot Icons for `moonblade`, `Mordenkainen's Force Blade`, `iron body`, `lich touch`, `Star Metal Cudgel` are not centered on oBG2

- `Iron body`.itm has an unknow icon 
- `Impervious Sanctity of Mind` has some wrong icons: unknown icon + mind shield + resist fear
- `static charge` has an icon in the main spell. However, it seems not necessary, as it is already in the spl#B.spl
- `wrath of the faithfull`B.spl has an unknown icon and `wrath of the faithfull`A.spl has an unknown icon + mind shield
- `wrath of the faithfull`A.spl immunity to hast does not protect agoinst mazzy haste (spin826.spl)
- ~`Entropy Shield`: there are some Opcode 318 with no state _~-- seems to be a compatibility issue with SCS
> - `Mind blank` has no icon 
> - `emotion, courage` has no icon
> - `emotion, hope` has not the right icon (heroism instead of hope)
> - `#beltyn` has berserk's icon in addition to beltyn's icon
> - `anti magic shell` has the wrong icon (spell failure instead of its icon)
> - `exaltation `has no icon
> - `Entropy shield` has a wrong icon; regeneration instead of entropy
> - `Blood Rage` has berserk's icon instead of blood rage
> - `animal rage` has 2 icons: animal rage and spell failure

> - ~put `install_obg2_icons=1` in `dw_iwdspells.ini` solve those issues. However, as you need to install a specific component to add icons, it seems strange to also need to modify `dw_iwdspells.ini` file to install some of them~ the ini file seems to have no effect in fact...

I have been misled by the component installation order: the icons issue is due to the installation of Component 50 after component 80 - as proposed - however, if you installed component 80 after it solves, this time, the issue.

**Comment by TotoR115** [comment]
when installing on BGT, there is a strange file created in the override folder: %val_bcs%.bcs

When looking a little bit, the error come from lib_sfo.tph line 485: 

> OUTER_SPRINT "%var%_BCS" "%val_bcs%"

it seems to be a typo and it seems that it should be 

> OUTER_SPRINT "%var%_BCS" "%val%"

**Comment by TotoR115** [comment]
When installed on oBG2 (maybe for EE too) There is a new ref for `CLERIC_CAUSE_SERIOUS_WOUNDS` and `CLERIC_CAUSE_CRITICAL_WOUNDS` witch are `CLERIC_CAUSE_SERIOUS_WOUNDS_IWD` and `CLERIC_CAUSE_CRITICAL_WOUNDS_IWD`. This create a double ref for the same spell for cleric

**Comment by TotoR115** [comment]
To be compatible with mod that alter amul15 - shield amulet effects with IRR and item pack are activated when equipped- it could be possible to add:

```
COPY_EXISTING ~amul15.itm~ ~override~ // update shield amulet to block MFM, too
	  LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 206 STR_VAR match_resource = ~spwi112~ resource = EVAL ~%WIZARD_MORDENKAINENS_FORCE_MISSILES%~ END
	  LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 206 STR_VAR match_resource = ~spwi112~ resource = EVAL ~%WIZARD_MORDENKAINENS_FORCE_MISSILES%b~ END  
```

**Comment by TotoR115** [comment]
> This is fine. There's no icon for paralysis immunity, and touch attacks generally include 1d2 damage as fist damage.

After all those years, I have never paid attention to those damages... every day something new 👍

**Comment by CamDawg** [comment]
> wrath of the faithfullA.spl immunity to hast does not protect agoinst mazzy haste (spin826.spl)

This is fixed.

The rest are icon issues, which are fixed, per the caveat below. There were basically three major issues at the root of all of them. 

- The library was was not gating new EE icons through an EE game check, so oBG2 ended up with fluid icon assignments and a three-column statdesc. This is why so many spells ended up with leftover 'unknown' icons or random ones. 
- The oBG2 icon component will now also purge redundant icons if a spell has a unique one, e.g. Iron Body will no longer show 'protection from poison' since it already has Iron Body. Without the oBG2 icons installed, these secondary icons will remain. 
- Somewhere deep in the SFO bits of code, oBG2 Icons get partially rolled back when a spell component (including bard songs) gets installed after. I've spent hours crawling through the code and can't find it, so I'm punting it to David. Everything works fine if oBG2 Icons are installed last, so I've restructured the mod to put them last in the natural order and will include this as a known issue in the readme until we can get it properly addressed.

**Comment by CamDawg** [comment]
IRR Shield Amulet vs. MFM is fixed, lib_sfo is fixed.

**Comment by TotoR115** [comment]
> This is by design. Enemy AI scripting still uses the unfettered non-IWD spells for simplicity, while PCs only see the new _IWD spell.

Ok, so now I understand, my mistake come from Divine Remix. As it reactivate all cleric spells, I have two version in my cleric spell book.
