### ISSUE TITLE
Elemental summoning bug

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/iwdification#15]
- The spell `Conjure Water elemental` summons air elemental: this bug is linked on oBG2 to the way the spell is created in elemental_summoning.tpa, replace_textually does not work with air elem spell ; `line 110`
- The description of all LESSER version of elemental summons are replace by Malavon's rage description; `line 88 does not seem to work as intended`
- The non-Lesser scroll's descriptions are wrong: a simple number replace them (3 for earth, 4 for fire et 5 for air) add line 74 `t_%v%` instead of `%v%` solve this

**Comment by CamDawg** [comment]
Cheers, fixed in https://github.com/Gibberlings3/iwdification/commit/884d89733c4f7a64401bf6f9671762cae66d482b
