### ISSUE TITLE
Small bugs #1 (oBG2)

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/iwdification#17]
> BAMs

- States in Character sheet page are not aligned as with vanilla BG2. this issue come from the dash (`-`) in states.bam. They are not 13x13 but 2x3... FWIW using offset does not seem to works with states.BAM file

- the ibclaw.bam of the claw weapon from the Beast Claw spell is not center. FYI the ground icon has a ref to a useless and non existing bam file... 

> shout (great) : 

- the projectile file (cdia315a.pro and cdia319a.pro) is missing the projectile animation (cdishout.bam does not exist) - should be `shoutt.bam`
- the fire sound in cdia315a.pro does not exist - should be `#FF_M100.WAV`
- CDIA431X.spl cast the cdia431V spell creating an additionnal shoutt animation which is not needed
- idem for CDIA806X.spl, it cast CDIA806V.SPL and create a not needed additionnal shoutt animation 

> Smashing wave : 
- the main spell has a projectile IDPRO302.pro (should not for oBG2)

**Comment by CamDawg** [comment]
Fixed, variously, in the following commits:

https://github.com/Gibberlings3/iwdification/commit/60eaa521ab3ba8092433e1ed6e56cc00e835743f
https://github.com/Gibberlings3/iwdification/commit/1c48c0c2aff888c406534d905282de3d3d281213
https://github.com/Gibberlings3/iwdification/commit/80a043b52bc8a051d607ec4d240da21d993b8ef7
https://github.com/Gibberlings3/iwdification/commit/98c1a0cd39c95882f446ba3caa0b58c55d4eb262
https://github.com/Gibberlings3/iwdification/commit/a71d718dfd8ba132cd0cde8594beeedb18864130
