### ISSUE TITLE
Minor incompatibility between iwdification and spell_rev over spcl213.spl prot from evil

### ISSUE THREAD

**Issue by porkchop-sandwiches** [Gibberlings3/iwdification#18]
I got a warning when installing component #100 of IWDification
WARNING: no effects altered on spcl213.spl

Checking the tp2 for IWDification it wanted to do this:
COPY_EXISTING ~spcl213.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_target = 2 target = 1 END
LPF ALTER_EFFECT INT_VAR match_duration = 60 duration = 7200 END
LPF ALTER_SPELL_HEADER INT_VAR target = 5 END // caster

I believe this updates spcl213 (prot from evil) to be target self, and to have a 24 hour duration for Paladins.  However the Spell Revisions mod, spell_rev, also updates spcl213 to increase the duration to 300.  I think this causes the above chunk of code for IWDification to fail to find spcl213 duration and update it as I had spell_rev installed first in my mod order.

I saw a few spots in the tp2 where there appear to be compatibility patches between other mods so I figured I would report this.  I'm not sure if a fix would require a full check that spell_rev exists and to handle it as a special case, or if match_duration could be changed to something else to be sure spcl213 duration is found and updated.

**Comment by CamDawg** [comment]
Thanks, this is fixed in https://github.com/Gibberlings3/iwdification/commit/556e05879d024e5abb1c375d9875d69e1930ec0b
