### ISSUE TITLE
RC2 - installation on oBG2

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/iwdification#8]
The actual release https://github.com/Gibberlings3/iwdification/commit/8991f8c00bb8926292efde6008bd2b5e48debc8f, have issues on oBG2 (don't know for EE) :

Component 40 : won't install - This issue was not present with the RC1 :

> ERROR locating resource for 'COPY'
Resource [%CLERIC_SMASHING_WAVE%.spl] not found in KEY file:
        [./chitin.key]
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.

> ERROR Installing [IWD Divine Spell Pack], rolling back to previous state

> WARNING: Unable to uninstall STRING_SET references from [iwdification/backup/40/UNSETSTR.40]: Invalid_argument("index out of bounds")

**Comment by CamDawg** [comment]
I'm not sure which exact commit fixed this, but everything now installs on oBG2.
