### ISSUE TITLE
Incompatibility between Bard class (IWD), cdtweak 2090, and Stratagems (3041, 3501, 4145, 4240, 5000) on oBG2

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/iwdification#9]
There is a weird incompatibility if IWDification bard class (RC1 or RC2) is installed with cdtweak component 2090 (no XP cap). All the following Stratagems components will fail (on oBG2 + BGT) : 
- 3041 (Arrows of Dispelling), 
- 3501 (Standardise spells between BG and BG2), 
- 4145 (Skip the Candlekeep tutorial), 
- 4240 (Treat mages' and priests' High-Level Abilities as innate), 
- 5000 (Ease-of-use party AI).

**Comment by CamDawg** [comment]
I'm closing this for IWDification. If this is still an issue in RC2, it's going to need to be fixed in Tweaks or SCS since they go after this in the stack.
